name: CI (Main)
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  statuses: write
  actions: read

jobs:
  build-main:
    strategy:
      matrix:
        os: [livius-win-self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Run the action
        run: echo "Running on ${{ runner.os }}"

      - name: Build
        shell: cmd
        run: |
          echo Build main...
          mkdir out
          echo hello > out\thing.txt


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main_bundle_${{ matrix.os }}
          path: out/

      - name: Map Repo A branch -> Repo B branch
        shell: pwsh
        id: map
        run: |
          if ("${{ github.event_name }}" -eq "pull_request") {
            $source_branch = "${{ github.head_ref }}"
          } else {
            $source_branch = "${{ github.ref_name }}"
          }

          Write-Host "Source branch is $source_branch"

          switch ($source_branch) {
            "v0" { "b_branch=feature/random-slave" | Out-File -FilePath $env:GITHUB_OUTPUT -Append }
            "v2" { "b_branch=feature/test-different-branch-slave" | Out-File -FilePath $env:GITHUB_OUTPUT -Append }
            default { "b_branch=main" | Out-File -FilePath $env:GITHUB_OUTPUT -Append }
          }


      - name: Trigger Resource (and set idle/pending status)
        if: ${{ success() }}
        uses: liviutomoiaga/shared_action/cascade-build-reporter@main
        with:
          op: trigger
          status_context: adi-resource-build
          status_state: pending
          resource_owner: liviutomoiaga
          resource_repo: resource_repo
          resource_event_type: adi-resource-trigger
          artifact_name: main-bundle
          resource_repo_branch: ${{ steps.map.outputs.b_branch }}
          github_token: ${{ secrets.GIT_TOKEN }}
          runner_os: ${{ matrix.os }}
